main: jeffersonctingle.page.App
name: DMTools-Lite
version: 0.1
api-version: 1.20
commands: 
  notery:
    description: Place an informative note!
    usage: /dnote
    aliases: [dnote, dmnote]
  mobi:
    description: Spawn a customized mob!
    usage: /mobi
    aliases: [mobicon, token]
  inti:
    description: interact with a mob!
    usage: /interact
    aliases: [interact]
  equip:
    description: change a mob's equipment
    usage: /equip
    aliases: [equip, loadout]
  grimoire:
    description: design custom spells
    usage: /grimoire
    aliases: [grimoire]
  game:
    description: Operates the core features of the DND architecture
    usage: /game
    aliases: [game]
  tools:
    description: big tool kit
    usage: /tools
    aliases: [toolbox, tools]
  